[project]
name = "sc-election-browser"
revision = "1.0"

[profiles.default]
DATABASE_URL = { description = "Database connection string", required = true }
GITHUB_TOKEN = { description = "GitHub token for accessing the GitHub API", required = true }
